name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build Capacitor App
        run: |
          npm run build
          npx cap add ios
          cd ios/App
          pod install
          xcodebuild -scheme App -sdk iphoneos -configuration Release

          